extends Object
class_name Nationality

## Enumeração de nacionalidades e funções utilitárias

enum Type {
	AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA_AND_BARBUDA, ARGENTINA, ARMENIA,
	AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS, BELGIUM,
	BELIZE, BENIN, BHUTAN, BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BRAZIL, BRUNEI_DARUSSALAM,
	BULGARIA, BURKINA_FASO, BURUNDI, CABO_VERDE, CAMBODIA, CAMEROON, CANADA,
	CENTRAL_AFRICAN_REPUBLIC, CHAD, CHILE, CHINA, COLOMBIA, COMOROS, CONGO, COSTA_RICA,
	COTE_DLVOIRE, CROATIA, CUBA, CYPRUS, CZECH_REPUBLIC, DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA,
	DEMOCRATIC_REPUBLIC_OF_THE_CONGO, DENMARK, DJIBOUTI, DOMINICA, DOMINICAN_REPUBLIC, ECUADOR,
	EGYPT, EL_SALVADOR, ENGLAND, EQUATORIAL_GUINEA, ERITREA, ESTONIA, ESWATINI, ETHIOPIA,
	EUROPEAN_UNION, FIJI, FINLAND, FRANCE, GABON, GAMBIA, GEORGIA, GERMANY, GHANA, GREECE,
	GRENADA, GUATEMALA, GUINEA, GUINEA_BISSAU, GUYANA, HAITI, HONDURAS, HUNGARY, ICELAND, INDIA,
	INDONESIA, IRAN, IRAQ, IRELAND, ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKHSTAN, KENYA,
	KIRIBATI, KUWAIT, KYRGYZSTAN, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN,
	LITHUANIA, LUXEMBURG, MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI, MALTA, MARSHALL_ISLANDS,
	MAURITANIA, MAURITIUS, MEXICO, MICRONESIA, MONACO, MONGOLIA, MONTENEGRO, MOROCCO,
	MOZAMBIQUE, MYANMAR, NAMIBIA, NAURU, NEPAL, NETHERLANDS, NEW_ZEALAND, NICARAGUA, NIGER,
	NIGERIA, NORTHERN_IRELAND, NORTHERN_IRELAND_ST_PATRICKS, NORTH_MACEDONIA, NORWAY, OMAN,
	PAKISTAN, PALAU, PALESTINE, PANAMA, PAPUA_NEW_GUINEA, PARAGUAY, PERU, PHILIPPINES, POLAND,
	PORTUGAL, QATAR, REPUBLIC_OF_KOREA, REPUBLIC_OF_MOLDOVA, ROMANIA, RUSSIAN_FEDERATION,
	RWANDA, SAINT_KITTS_AND_NEVIS, SAINT_LUCIA, SAINT_VINCENT_AND_THE_GRENADINES, SAMOA,
	SAN_MARINO, SAO_TOME_AND_PRINCIPE, SAUDI_ARABIA, SCOTLAND, SENEGAL, SERBIA, SEYCHELLES,
	SIERRA_LEONE, SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON_ISLANDS, SOMALIA, SOUTH_AFRICA,
	SOUTH_SUDAN, SPAIN, SRI_LANKA, SUDAN, SURINAME, SWEDEN, SWITZERLAND, SYRIAN_ARAB_REPUBLIC,
	TAIWAN, TAJIKISTAN, THAILAND, TIMOR_LESTE, TOGO, TONGA, TRINIDAD_AND_TOBAGO, TUNISIA,
	TURKEY, TURKMENISTAN, TUVALU, UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, UNITED_KINGDOM,
	UNITED_REPUBLIC_OF_TANZANIA, UNITED_STATES_OF_AMERICA, URUGUAY, UZBEKISTAN, VANUATU,
	VATICAN_CITY, VENEZUELA, VEXILLOLOGY, VIET_NAM, WALES, YEMEN, ZAMBIA, ZIMBABWE
}


static func get_flag_path(nat: Type) -> String:
	"""Retorna o caminho da textura da bandeira para a nacionalidade especificada"""
	var nationality_names = {
		Type.AFGHANISTAN: "Afghanistan",
		Type.ALBANIA: "Albania",
		Type.ALGERIA: "Algeria",
		Type.ANDORRA: "Andorra",
		Type.ANGOLA: "Angola",
		Type.ANTIGUA_AND_BARBUDA: "AntiguaAndBarbuda",
		Type.ARGENTINA: "Argentina",
		Type.ARMENIA: "Armenia",
		Type.AUSTRALIA: "Australia",
		Type.AUSTRIA: "Austria",
		Type.AZERBAIJAN: "Azerbaijan",
		Type.BAHAMAS: "Bahamas",
		Type.BAHRAIN: "Bahrain",
		Type.BANGLADESH: "Bangladesh",
		Type.BARBADOS: "Barbados",
		Type.BELARUS: "Belarus",
		Type.BELGIUM: "Belgium",
		Type.BELIZE: "Belize",
		Type.BENIN: "Benin",
		Type.BHUTAN: "Bhutan",
		Type.BOLIVIA: "Bolivia",
		Type.BOSNIA_AND_HERZEGOVINA: "BosniaAndHerzegovina",
		Type.BOTSWANA: "Botswana",
		Type.BRAZIL: "Brazil",
		Type.BRUNEI_DARUSSALAM: "BruneiDarussalam",
		Type.BULGARIA: "Bulgaria",
		Type.BURKINA_FASO: "BurkinaFaso",
		Type.BURUNDI: "Burundi",
		Type.CABO_VERDE: "CaboVerde",
		Type.CAMBODIA: "Cambodia",
		Type.CAMEROON: "Cameroon",
		Type.CANADA: "Canada",
		Type.CENTRAL_AFRICAN_REPUBLIC: "CentralAfricanRepublic",
		Type.CHAD: "Chad",
		Type.CHILE: "Chile",
		Type.CHINA: "China",
		Type.COLOMBIA: "Colombia",
		Type.COMOROS: "Comoros",
		Type.CONGO: "Congo",
		Type.COSTA_RICA: "CostaRica",
		Type.COTE_DLVOIRE: "CoteDlvoire",
		Type.CROATIA: "Croatia",
		Type.CUBA: "Cuba",
		Type.CYPRUS: "Cyprus",
		Type.CZECH_REPUBLIC: "CzechRepublic",
		Type.DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA: "DemocraticPeoplesRepublicOfKorea",
		Type.DEMOCRATIC_REPUBLIC_OF_THE_CONGO: "DemocraticRepublicOfTheCongo",
		Type.DENMARK: "Denmark",
		Type.DJIBOUTI: "Djibouti",
		Type.DOMINICA: "Dominica",
		Type.DOMINICAN_REPUBLIC: "DominicanRepublic",
		Type.ECUADOR: "Ecuador",
		Type.EGYPT: "Egypt",
		Type.EL_SALVADOR: "ElSalvador",
		Type.ENGLAND: "England",
		Type.EQUATORIAL_GUINEA: "EquatorialGuinea",
		Type.ERITREA: "Eritrea",
		Type.ESTONIA: "Estonia",
		Type.ESWATINI: "Eswatini",
		Type.ETHIOPIA: "Ethiopia",
		Type.EUROPEAN_UNION: "EuropeanUnion",
		Type.FIJI: "Fiji",
		Type.FINLAND: "Finland",
		Type.FRANCE: "France",
		Type.GABON: "Gabon",
		Type.GAMBIA: "Gambia",
		Type.GEORGIA: "Georgia",
		Type.GERMANY: "Germany",
		Type.GHANA: "Ghana",
		Type.GREECE: "Greece",
		Type.GRENADA: "Grenada",
		Type.GUATEMALA: "Guatemala",
		Type.GUINEA: "Guinea",
		Type.GUINEA_BISSAU: "GuineaBissau",
		Type.GUYANA: "Guyana",
		Type.HAITI: "Haiti",
		Type.HONDURAS: "Honduras",
		Type.HUNGARY: "Hungary",
		Type.ICELAND: "Iceland",
		Type.INDIA: "India",
		Type.INDONESIA: "Indonesia",
		Type.IRAN: "Iran",
		Type.IRAQ: "Iraq",
		Type.IRELAND: "Ireland",
		Type.ISRAEL: "Israel",
		Type.ITALY: "Italy",
		Type.JAMAICA: "Jamaica",
		Type.JAPAN: "Japan",
		Type.JORDAN: "Jordan",
		Type.KAZAKHSTAN: "Kazakhstan",
		Type.KENYA: "Kenya",
		Type.KIRIBATI: "Kiribati",
		Type.KUWAIT: "Kuwait",
		Type.KYRGYZSTAN: "Kyrgyzstan",
		Type.LATVIA: "Latvia",
		Type.LEBANON: "Lebanon",
		Type.LESOTHO: "Lesotho",
		Type.LIBERIA: "Liberia",
		Type.LIBYA: "Libya",
		Type.LIECHTENSTEIN: "Liechtenstein",
		Type.LITHUANIA: "Lithuania",
		Type.LUXEMBURG: "Luxemburg",
		Type.MADAGASCAR: "Madagascar",
		Type.MALAWI: "Malawi",
		Type.MALAYSIA: "Malaysia",
		Type.MALDIVES: "Maldives",
		Type.MALI: "Mali",
		Type.MALTA: "Malta",
		Type.MARSHALL_ISLANDS: "MarshallIslands",
		Type.MAURITANIA: "Mauritania",
		Type.MAURITIUS: "Mauritius",
		Type.MEXICO: "Mexico",
		Type.MICRONESIA: "Micronesia",
		Type.MONACO: "Monaco",
		Type.MONGOLIA: "Mongolia",
		Type.MONTENEGRO: "Montenegro",
		Type.MOROCCO: "Morocco",
		Type.MOZAMBIQUE: "Mozambique",
		Type.MYANMAR: "Myanmar",
		Type.NAMIBIA: "Namibia",
		Type.NAURU: "Nauru",
		Type.NEPAL: "Nepal",
		Type.NETHERLANDS: "Netherlands",
		Type.NEW_ZEALAND: "NewZealand",
		Type.NICARAGUA: "Nicaragua",
		Type.NIGER: "Niger",
		Type.NIGERIA: "Nigeria",
		Type.NORTHERN_IRELAND: "NorthernIreland",
		Type.NORTHERN_IRELAND_ST_PATRICKS: "NorthernIrelandStPatricks",
		Type.NORTH_MACEDONIA: "NorthMacedonia",
		Type.NORWAY: "Norway",
		Type.OMAN: "Oman",
		Type.PAKISTAN: "Pakistan",
		Type.PALAU: "Palau",
		Type.PALESTINE: "Palestine",
		Type.PANAMA: "Panama",
		Type.PAPUA_NEW_GUINEA: "PapuaNewGuinea",
		Type.PARAGUAY: "Paraguay",
		Type.PERU: "Peru",
		Type.PHILIPPINES: "Philippines",
		Type.POLAND: "Poland",
		Type.PORTUGAL: "Portugal",
		Type.QATAR: "Qatar",
		Type.REPUBLIC_OF_KOREA: "RepublicOfKorea",
		Type.REPUBLIC_OF_MOLDOVA: "RepublicOfMoldova",
		Type.ROMANIA: "Romania",
		Type.RUSSIAN_FEDERATION: "RussianFederation",
		Type.RWANDA: "Rwanda",
		Type.SAINT_KITTS_AND_NEVIS: "SaintKittsAndNevis",
		Type.SAINT_LUCIA: "SaintLucia",
		Type.SAINT_VINCENT_AND_THE_GRENADINES: "SaintVincentAndTheGrenadines",
		Type.SAMOA: "Samoa",
		Type.SAN_MARINO: "SanMarino",
		Type.SAO_TOME_AND_PRINCIPE: "SaoTomeAndPrincipe",
		Type.SAUDI_ARABIA: "SaudiArabia",
		Type.SCOTLAND: "Scotland",
		Type.SENEGAL: "Senegal",
		Type.SERBIA: "Serbia",
		Type.SEYCHELLES: "Seychelles",
		Type.SIERRA_LEONE: "SierraLeone",
		Type.SINGAPORE: "Singapore",
		Type.SLOVAKIA: "Slovakia",
		Type.SLOVENIA: "Slovenia",
		Type.SOLOMON_ISLANDS: "SolomonIslands",
		Type.SOMALIA: "Somalia",
		Type.SOUTH_AFRICA: "SouthAfrica",
		Type.SOUTH_SUDAN: "SouthSudan",
		Type.SPAIN: "Spain",
		Type.SRI_LANKA: "SriLanka",
		Type.SUDAN: "Sudan",
		Type.SURINAME: "Suriname",
		Type.SWEDEN: "Sweden",
		Type.SWITZERLAND: "Switzerland",
		Type.SYRIAN_ARAB_REPUBLIC: "SyrianArabRepublic",
		Type.TAIWAN: "Taiwan",
		Type.TAJIKISTAN: "Tajikistan",
		Type.THAILAND: "Thailand",
		Type.TIMOR_LESTE: "TimorLeste",
		Type.TOGO: "Togo",
		Type.TONGA: "Tonga",
		Type.TRINIDAD_AND_TOBAGO: "TrinidadAndTobago",
		Type.TUNISIA: "Tunisia",
		Type.TURKEY: "Turkey",
		Type.TURKMENISTAN: "Turkmenistan",
		Type.TUVALU: "Tuvalu",
		Type.UGANDA: "Uganda",
		Type.UKRAINE: "Ukraine",
		Type.UNITED_ARAB_EMIRATES: "UnitedArabEmirates",
		Type.UNITED_KINGDOM: "UnitedKingdom",
		Type.UNITED_REPUBLIC_OF_TANZANIA: "UnitedRepublicOfTanzania",
		Type.UNITED_STATES_OF_AMERICA: "UnitedStatesOfAmerica",
		Type.URUGUAY: "Uruguay",
		Type.UZBEKISTAN: "Uzbekistan",
		Type.VANUATU: "Vanuatu",
		Type.VATICAN_CITY: "VaticanCity",
		Type.VENEZUELA: "Venezuela",
		Type.VEXILLOLOGY: "Vexillology",
		Type.VIET_NAM: "VietNam",
		Type.WALES: "Wales",
		Type.YEMEN: "Yemen",
		Type.ZAMBIA: "Zambia",
		Type.ZIMBABWE: "Zimbabwe"
	}
	
	var flag_name = nationality_names.get(nat, "Japan")
	return "res://assets/sprites/UIs/icons/flags/rectangle_24x16/" + flag_name + ".png"
